---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.fullnameOverride }}"
  labels:
    app: "{{ .Values.fullnameOverride }}"
data:
  application.yml: |-
    omar:
      lite:
        wms:
          database:
            name: {{ .Values.global.omarDb.name }}
            username: {{ .Values.global.omarDb.user }}
            password: {{ .Values.global.omarDb.password }}
            host: {{ .Values.global.omarDb.host }}
            port: {{ .Values.global.omarDb.port }}
          styles:
            blacksky:
              filter: mission_id='BlackSky'
              params:
                bands: default
                hist_op: none
                null_pixel_flip:  'false'
            skysat:
              filter: mission_id='SkySat'
              params:
                bands: default
                hist_op: std-stretch-2
                null_pixel_flip:  'false'
    micronaut:
      config-client:
        enabled: false
      http:
        client:
          read-idle-timeout: -1

    kubernetes:
      client:
        secure: true
        secrets:
          enabled: true
        discovery:
          enabled: false
