{{- $annotations := merge .Values.deployment.annotations $.Values.global.deployment.annotations -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {}
  name: {{ .Values.fullnameOverride }}
  annotations:
  {{- range $key, $value := $annotations }}
    {{- $key | nindent 4 }}: {{ tpl $value $ | quote }}
  {{- end }}
spec:
  {{- if eq (include "omar-foobar.autoscaling.enabled" $) "false" }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.fullnameOverride }}
  template:
    metadata:
      labels:
        app: {{ .Values.fullnameOverride }}
    spec:
      containers:
        - name:  {{ .Values.fullnameOverride }}
          env:
          {{- include "omar-foobar.envVars" . | indent 8 }}
          {{- if .Values.imageSkaffoldOverride }}
          image: {{ .Values.imageSkaffoldOverride }}
          {{- else }}
          image: {{ include "omar-foobar.image" . | quote }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            httpGet:
              path: {{ .Values.ingressPath }}{{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port }}
              scheme: HTTP
          readinessProbe:
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            httpGet:
              path: {{ .Values.ingressPath }}{{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port }}
              scheme: HTTP
          ports:
            - containerPort: {{ .Values.internalPort }}
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          volumeMounts:
{{- include "omar-foobar.volumeMounts" . | indent 12 }}
      dnsPolicy: ClusterFirst
        {{- if .Values.global.useImagePullSecret }}
      imagePullSecrets:
        # - name: {{ .Values.fullnameOverride }}-pull-secret
        - name: omar-lite-wms-pull-secret
        {{- end }}
      restartPolicy: Always
      securityContext: {}
      serviceAccountName: {{ include "omar-foobar.serviceAccount.name" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
{{- include "omar-foobar.volumes" . | indent 8 }}
