apiVersion: apps/v1
kind: Deployment
metadata:
  name: "omar-foobar"
spec:
  selector:
    matchLabels:
      app: "omar-foobar"
  template:
    metadata:
      labels:
        app: "omar-foobar"
    spec:
      containers:
        - name: "omar-foobar"
          image: "nexus-docker-private-hosted.ossim.io/omar-foobar"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "omar-foobar"
spec:
  selector:
    app: "omar-foobar"
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8080
